#!/usr/bin/env node
'use strict';

function parseJSON(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

const ArgumentParser = require('argparse').ArgumentParser;
const fs = require('fs');
const path = require('path');
const pkg = parseJSON(path.join(__dirname, 'package.json'));

const argParser = new ArgumentParser({
  addHelp: true,
  description: 'Swagger API client generator CLI for Angular 2+ projects.',
  version: pkg.version,
});
argParser.addArgument(['-i', '--input'], {
  action: 'store',
  dest: 'config',
  help: 'The swagger-gen CLI configuration file.',
});
argParser.addArgument(['-o', '--operation'], {
  action: 'store',
  choices: ['compare', 'generate', 'update'],
  dest: 'operation',
  help: 'Desired operation that should be executed.',
});

const args = argParser.parseArgs();
const config = args.config;
const configExists = fs.existsSync(config);

if (configExists) {
  const options = parseJSON(config);

  run({ configurations: options.configurations, operation: args.operation });
} else {
  argParser.parseArgs(['--help']);
}

function run(options) {
  const ngSwaggerGenCli = require('./ng-swagger-gen-cli.js');
  ngSwaggerGenCli(options);
}
